# Generated by Django 5.0.6 on 2026-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(max_length=500),
        ),
    ]
